<a href="https://colab.research.google.com/github/djawed-bkh/-Hacktober-fest-2021/blob/master/Naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Théoreme de bayes en python
    En utilisant le dataset iris
    La régle: P(class|data) = (P(data|class) * P(class)) / P(data)
    

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [ ]:
iris=load_iris()
iris.data[1:5]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

### Attributs des fleurs

In [ ]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

### Les classes 

In [ ]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
X_train, X_tests, Y_train, Y_tests= train_test_split(iris.data,iris.target,test_size=0.3, random_state=108)


## Phase d'apprentissage a travers GaussianNB()

In [ ]:
Gaussian_classifier=GaussianNB()
Gaussian_classifier.fit(X_train,Y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

## Phase de test 

In [ ]:
Y_pred=Gaussian_classifier.predict(X_tests)
Y_pred

array([0, 0, 1, 1, 1, 2, 1, 0, 2, 2, 2, 1, 0, 2, 0, 0, 0, 0, 0, 1, 1, 0,
       2, 0, 2, 1, 0, 0, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 2,
       1])

## Voir le pourcentage d'apprentissage

In [ ]:
from sklearn import metrics
print("Precision:",metrics.accuracy_score(Y_tests, Y_pred))

Precision: 0.9333333333333333
